"""empty message

Revision ID: 8e7907bdc3ec
Revises: 
Create Date: 2023-02-06 11:40:28.840266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7907bdc3ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profissao', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudante', schema=None) as batch_op:
        batch_op.drop_column('profissao')

    # ### end Alembic commands ###
